name: Run Hardhat Test with NPM

on:
  push:
  workflow_dispatch:

jobs:
  test_hardhat_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: NPM Clean Install
        run: npm ci
      - name: Hardhat Compile
        run: npx hardhat compile
      - name: Hardhat Test
        run: npx hardhat test
      - name: Hardhat Coverage Result
        run: npx hardhat coverage